### ISSUE TITLE
Conversion of .csr to .cer

### ISSUE THREAD

**Issue by jeydave** [project-imas/mdm-server#8]
How can I convert the customer.csr to .cer? Looks as if the link provided in the ReadMe is outdated and the new Cert generation site asks us to select the correct environment (Development or Production). I am stuck in finding this. Any help is much appreciated. Thanks.

**Comment by thrasr** [comment]
I'm going to go ahead and close this due to inactivity and a solved problem.  The solution to this issue is to go to [this link](https://developer.apple.com/account/ios/certificate/certificateCreate.action) or click the '+' on the Certificates, Identifiers & Profiles page.  For the type of certificiate, you'll want to choose MDM CSR (under production).  If this option is grayed out and unavailable, you'll need to contact apple with a request to enable it for your account.  You can either send apple an email, call them, or go through the support page on the developer portal.  They usually enable the option within a couple of days.
